services:
  reservas_web:
    build:
      context: ./ab_reservas_project
      dockerfile: Dockerfile
    container_name: ab-reservas-web
    env_file:
      - ./ab_reservas_project/.env
    volumes:
      - ./ab_reservas_project:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    # command: poetry run uvicorn ab_reservas_project.asgi:application --host 0.0.0.0 --port 8000 --reload
    command: poetry run python manage.py runserver 0.0.0.0:8000


  db:
    image: postgres:16-alpine
    container_name: ab-reservas-db
    env_file:
      - ./ab_reservas_project/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
